#############################################################################
# Makefile for building: ABR_server.app/Contents/MacOS/ABR_server
# Generated by qmake (2.01a) (Qt 4.7.1) on: Tue Nov 19 16:16:02 2013
# Project:  ABR_server.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.7/mkspecs/macx-g++ -o Makefile ABR_server.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.7/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtNetwork.framework/Versions/4/Headers -I/usr/include/QtNetwork -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/Library/Frameworks/QtOpenGL.framework/Versions/4/Headers -I/usr/include/QtOpenGL -I/usr/include -I/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/System/Library/Frameworks/AGL.framework/Headers -I. -I. -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework QtOpenGL -framework QtGui -framework QtNetwork -framework QtCore -framework OpenGL -framework AGL 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		servermainwindow.cpp \
		phone_item.cpp \
		android_dialog.cpp \
		camera_udp_object.cpp \
		android_tcp_object.cpp \
		android_tcp_server.cpp \
		sensors_udp_object.cpp \
		ioio_udp_object.cpp moc_servermainwindow.cpp \
		moc_phone_item.cpp \
		moc_android_dialog.cpp \
		moc_camera_udp_object.cpp \
		moc_android_tcp_object.cpp \
		moc_android_tcp_server.cpp \
		moc_sensors_udp_object.cpp \
		moc_ioio_udp_object.cpp \
		qrc_CARL_resources.cpp
OBJECTS       = main.o \
		servermainwindow.o \
		phone_item.o \
		android_dialog.o \
		camera_udp_object.o \
		android_tcp_object.o \
		android_tcp_server.o \
		sensors_udp_object.o \
		ioio_udp_object.o \
		moc_servermainwindow.o \
		moc_phone_item.o \
		moc_android_dialog.o \
		moc_camera_udp_object.o \
		moc_android_tcp_object.o \
		moc_android_tcp_server.o \
		moc_sensors_udp_object.o \
		moc_ioio_udp_object.o \
		qrc_CARL_resources.o
DIST          = /usr/local/Qt4.7/mkspecs/common/unix.conf \
		/usr/local/Qt4.7/mkspecs/common/mac.conf \
		/usr/local/Qt4.7/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.7/mkspecs/qconfig.pri \
		/usr/local/Qt4.7/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.7/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.7/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.7/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.7/mkspecs/features/debug.prf \
		/usr/local/Qt4.7/mkspecs/features/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.7/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.7/mkspecs/features/qt.prf \
		/usr/local/Qt4.7/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt4.7/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.7/mkspecs/features/moc.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.7/mkspecs/features/resources.prf \
		/usr/local/Qt4.7/mkspecs/features/uic.prf \
		/usr/local/Qt4.7/mkspecs/features/yacc.prf \
		/usr/local/Qt4.7/mkspecs/features/lex.prf \
		/usr/local/Qt4.7/mkspecs/features/include_source_dir.prf \
		ABR_server.pro
QMAKE_TARGET  = ABR_server
DESTDIR       = 
TARGET        = ABR_server.app/Contents/MacOS/ABR_server

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile ABR_server.app/Contents/PkgInfo ABR_server.app/Contents/Resources/empty.lproj ABR_server.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_servermainwindow.h ui_android_dialog.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) ABR_server.app/Contents/MacOS/ || $(MKDIR) ABR_server.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ABR_server.pro  /usr/local/Qt4.7/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.7/mkspecs/common/unix.conf \
		/usr/local/Qt4.7/mkspecs/common/mac.conf \
		/usr/local/Qt4.7/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.7/mkspecs/qconfig.pri \
		/usr/local/Qt4.7/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.7/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.7/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.7/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.7/mkspecs/features/debug.prf \
		/usr/local/Qt4.7/mkspecs/features/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.7/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.7/mkspecs/features/qt.prf \
		/usr/local/Qt4.7/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt4.7/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.7/mkspecs/features/moc.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.7/mkspecs/features/resources.prf \
		/usr/local/Qt4.7/mkspecs/features/uic.prf \
		/usr/local/Qt4.7/mkspecs/features/yacc.prf \
		/usr/local/Qt4.7/mkspecs/features/lex.prf \
		/usr/local/Qt4.7/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/QtOpenGL.framework/QtOpenGL.prl \
		/Library/Frameworks/QtGui.framework/QtGui.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl \
		/Library/Frameworks/QtNetwork.framework/QtNetwork.prl
	$(QMAKE) -spec /usr/local/Qt4.7/mkspecs/macx-g++ -o Makefile ABR_server.pro
/usr/local/Qt4.7/mkspecs/common/unix.conf:
/usr/local/Qt4.7/mkspecs/common/mac.conf:
/usr/local/Qt4.7/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.7/mkspecs/qconfig.pri:
/usr/local/Qt4.7/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Qt4.7/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.7/mkspecs/features/qt_config.prf:
/usr/local/Qt4.7/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.7/mkspecs/features/default_pre.prf:
/usr/local/Qt4.7/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.7/mkspecs/features/mac/dwarf2.prf:
/usr/local/Qt4.7/mkspecs/features/debug.prf:
/usr/local/Qt4.7/mkspecs/features/default_post.prf:
/usr/local/Qt4.7/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.7/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.7/mkspecs/features/warn_on.prf:
/usr/local/Qt4.7/mkspecs/features/qt.prf:
/usr/local/Qt4.7/mkspecs/features/unix/opengl.prf:
/usr/local/Qt4.7/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.7/mkspecs/features/moc.prf:
/usr/local/Qt4.7/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.7/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.7/mkspecs/features/resources.prf:
/usr/local/Qt4.7/mkspecs/features/uic.prf:
/usr/local/Qt4.7/mkspecs/features/yacc.prf:
/usr/local/Qt4.7/mkspecs/features/lex.prf:
/usr/local/Qt4.7/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/QtOpenGL.framework/QtOpenGL.prl:
/Library/Frameworks/QtGui.framework/QtGui.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
/Library/Frameworks/QtNetwork.framework/QtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.7/mkspecs/macx-g++ -o Makefile ABR_server.pro

ABR_server.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) ABR_server.app/Contents || $(MKDIR) ABR_server.app/Contents 
	@$(DEL_FILE) ABR_server.app/Contents/PkgInfo
	@echo "APPL????" >ABR_server.app/Contents/PkgInfo
ABR_server.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) ABR_server.app/Contents/Resources || $(MKDIR) ABR_server.app/Contents/Resources 
	@touch ABR_server.app/Contents/Resources/empty.lproj
	
ABR_server.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) ABR_server.app/Contents || $(MKDIR) ABR_server.app/Contents 
	@$(DEL_FILE) ABR_server.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,ABR_server,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.7/mkspecs/macx-g++/Info.plist.app >ABR_server.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/ABR_server1.0.0 || $(MKDIR) .tmp/ABR_server1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ABR_server1.0.0/ && $(COPY_FILE) --parents servermainwindow.h phone_item.h android_dialog.h camera_udp_object.h android_tcp_object.h android_tcp_server.h sensors_udp_object.h ioio_udp_object.h .tmp/ABR_server1.0.0/ && $(COPY_FILE) --parents CARL_resources.qrc .tmp/ABR_server1.0.0/ && $(COPY_FILE) --parents main.cpp servermainwindow.cpp phone_item.cpp android_dialog.cpp camera_udp_object.cpp android_tcp_object.cpp android_tcp_server.cpp sensors_udp_object.cpp ioio_udp_object.cpp .tmp/ABR_server1.0.0/ && $(COPY_FILE) --parents servermainwindow.ui android_dialog.ui .tmp/ABR_server1.0.0/ && (cd `dirname .tmp/ABR_server1.0.0` && $(TAR) ABR_server1.0.0.tar ABR_server1.0.0 && $(COMPRESS) ABR_server1.0.0.tar) && $(MOVE) `dirname .tmp/ABR_server1.0.0`/ABR_server1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ABR_server1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r ABR_server.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_servermainwindow.cpp moc_phone_item.cpp moc_android_dialog.cpp moc_camera_udp_object.cpp moc_android_tcp_object.cpp moc_android_tcp_server.cpp moc_sensors_udp_object.cpp moc_ioio_udp_object.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_servermainwindow.cpp moc_phone_item.cpp moc_android_dialog.cpp moc_camera_udp_object.cpp moc_android_tcp_object.cpp moc_android_tcp_server.cpp moc_sensors_udp_object.cpp moc_ioio_udp_object.cpp
moc_servermainwindow.cpp: servermainwindow.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ servermainwindow.h -o moc_servermainwindow.cpp

moc_phone_item.cpp: phone_item.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ phone_item.h -o moc_phone_item.cpp

moc_android_dialog.cpp: android_dialog.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ android_dialog.h -o moc_android_dialog.cpp

moc_camera_udp_object.cpp: camera_udp_object.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ camera_udp_object.h -o moc_camera_udp_object.cpp

moc_android_tcp_object.cpp: android_tcp_object.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ android_tcp_object.h -o moc_android_tcp_object.cpp

moc_android_tcp_server.cpp: android_tcp_server.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ android_tcp_server.h -o moc_android_tcp_server.cpp

moc_sensors_udp_object.cpp: sensors_udp_object.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ sensors_udp_object.h -o moc_sensors_udp_object.cpp

moc_ioio_udp_object.cpp: ioio_udp_object.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ioio_udp_object.h -o moc_ioio_udp_object.cpp

compiler_rcc_make_all: qrc_CARL_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_CARL_resources.cpp
qrc_CARL_resources.cpp: CARL_resources.qrc \
		Image_files/carl_logo.jpg \
		Image_files/left_arrow.png \
		Image_files/down_arrow.png \
		Image_files/up_arrow.png \
		Image_files/right_arrow.png \
		Image_files/android_logo.jpg \
		Image_files/android_logo2.jpg
	/Developer/Tools/Qt/rcc -name CARL_resources CARL_resources.qrc -o qrc_CARL_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_servermainwindow.h ui_android_dialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_servermainwindow.h ui_android_dialog.h
ui_servermainwindow.h: servermainwindow.ui
	/Developer/Tools/Qt/uic servermainwindow.ui -o ui_servermainwindow.h

ui_android_dialog.h: android_dialog.ui
	/Developer/Tools/Qt/uic android_dialog.ui -o ui_android_dialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp servermainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

servermainwindow.o: servermainwindow.cpp servermainwindow.h \
		ui_servermainwindow.h \
		android_dialog.h \
		phone_item.h \
		android_tcp_server.h \
		android_tcp_object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o servermainwindow.o servermainwindow.cpp

phone_item.o: phone_item.cpp phone_item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o phone_item.o phone_item.cpp

android_dialog.o: android_dialog.cpp android_dialog.h \
		ui_android_dialog.h \
		android_tcp_object.h \
		camera_udp_object.h \
		sensors_udp_object.h \
		ioio_udp_object.h \
		phone_item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o android_dialog.o android_dialog.cpp

camera_udp_object.o: camera_udp_object.cpp camera_udp_object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera_udp_object.o camera_udp_object.cpp

android_tcp_object.o: android_tcp_object.cpp android_tcp_object.h \
		servermainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o android_tcp_object.o android_tcp_object.cpp

android_tcp_server.o: android_tcp_server.cpp android_tcp_server.h \
		servermainwindow.h \
		android_tcp_object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o android_tcp_server.o android_tcp_server.cpp

sensors_udp_object.o: sensors_udp_object.cpp sensors_udp_object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sensors_udp_object.o sensors_udp_object.cpp

ioio_udp_object.o: ioio_udp_object.cpp ioio_udp_object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ioio_udp_object.o ioio_udp_object.cpp

moc_servermainwindow.o: moc_servermainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_servermainwindow.o moc_servermainwindow.cpp

moc_phone_item.o: moc_phone_item.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_phone_item.o moc_phone_item.cpp

moc_android_dialog.o: moc_android_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_android_dialog.o moc_android_dialog.cpp

moc_camera_udp_object.o: moc_camera_udp_object.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_camera_udp_object.o moc_camera_udp_object.cpp

moc_android_tcp_object.o: moc_android_tcp_object.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_android_tcp_object.o moc_android_tcp_object.cpp

moc_android_tcp_server.o: moc_android_tcp_server.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_android_tcp_server.o moc_android_tcp_server.cpp

moc_sensors_udp_object.o: moc_sensors_udp_object.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sensors_udp_object.o moc_sensors_udp_object.cpp

moc_ioio_udp_object.o: moc_ioio_udp_object.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ioio_udp_object.o moc_ioio_udp_object.cpp

qrc_CARL_resources.o: qrc_CARL_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_CARL_resources.o qrc_CARL_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

